"""ReCAP: ReAct Agent with Contract-based Guardrails (基于阶段间合同的 ReAct Agent 合规护栏)."""

from recap.schemas import (
    # Enums
    TrustLevel,
    DataSource,
    ExecutionStatus,
    ViolationType,
    RecoveryAction,
    ObligationStatus,
    AuthorityBasis,
    ConstraintValueType,
    ConstraintOperator,
    # Core data models
    Constraint,
    IntentCertificate,
    ActionEvent,
    ObservationEvent,
    ViolationEvidence,
    TransitionResult,
    # Ledger entries
    TaskEntry,
    IntentEntry,
    ActionEntry,
    ObservationEntry,
    ObligationEntry,
    ViolationEntry,
    RepairEntry,
    ReplanEntry,
    LedgerEntry,
)

from recap.graph import (
    ReCAPState,
    ScenarioConfig,
    set_llm,
    set_scenario,
    init_node,
    think_node,
    act_node,
    observe_node,
    think_act_check_node,
    act_observe_check_node,
    observe_think_check_node,
    repair_node,
    replan_node,
    should_continue_after_think,
    route_after_think_act_check,
    route_after_act_observe_check,
    route_after_observe_think_check,
    build_recap_graph,
)

from recap.ledger import (
    EvidenceDetector,
    collect_evidence,
    evidence_sources,
    source_tool_for,
    LedgerStore,
    generate_run_ledger_path,
    get_ledger_store,
    reset_ledger_store,
)

from recap.tools import (
    ToolExecutor,
    MultiprocessingToolExecutor,
    DirectToolExecutor,
    DeterministicToolError,
)

__all__ = [
    # Enums
    "TrustLevel",
    "DataSource",
    "ExecutionStatus",
    "ViolationType",
    "RecoveryAction",
    "ObligationStatus",
    "AuthorityBasis",
    "ConstraintValueType",
    "ConstraintOperator",
    # Core data models
    "Constraint",
    "IntentCertificate",
    "ActionEvent",
    "ObservationEvent",
    "ViolationEvidence",
    "TransitionResult",
    # Ledger entries
    "TaskEntry",
    "IntentEntry",
    "ActionEntry",
    "ObservationEntry",
    "ObligationEntry",
    "ViolationEntry",
    "RepairEntry",
    "ReplanEntry",
    "LedgerEntry",
    # Graph
    "ReCAPState",
    "ScenarioConfig",
    "set_llm",
    "set_scenario",
    "init_node",
    "think_node",
    "act_node",
    "observe_node",
    "think_act_check_node",
    "act_observe_check_node",
    "observe_think_check_node",
    "repair_node",
    "replan_node",
    "should_continue_after_think",
    "route_after_think_act_check",
    "route_after_act_observe_check",
    "route_after_observe_think_check",
    "build_recap_graph",
    # Ledger
    "EvidenceDetector",
    "collect_evidence",
    "evidence_sources",
    "source_tool_for",
    "LedgerStore",
    "generate_run_ledger_path",
    "get_ledger_store",
    "reset_ledger_store",
    # Tool executor
    "ToolExecutor",
    "MultiprocessingToolExecutor",
    "DirectToolExecutor",
    "DeterministicToolError",
]
